package Menus.Panel;

import java.util.ArrayList;

import javax.swing.table.DefaultTableModel;

import Objects.Booking;
import Objects.BookingDataFile;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author William
 */
public class ClientHome extends javax.swing.JPanel {

    /**
     * Creates new form HomeClient
     */
    public ClientHome(String ClientID) {
        initComponents();
        TableOngoingBooking.getColumnModel().getColumn(0).setPreferredWidth(200);
        DefaultTableModel model = (DefaultTableModel) TableOngoingBooking.getModel();
        model.setRowCount(0);

        BookingDataFile bdf = new BookingDataFile("src\\caroodj\\Data\\Booking.txt");
        String[] bookingQuery = {"*", "*", "*", "false", "*", "*",ClientID};
        
        ArrayList<Booking> bookingList = bdf.queryDatabase(bdf.createQuery(bookingQuery)).all();

        for (Booking booking : bookingList) {
            model.addRow(new Object[] {booking.getId(), booking.car.manufacture, booking.car.model, 
                booking.car.year, booking.car.rentalCost, booking.startDate, booking.endDate});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        MottoPanel = new javax.swing.JPanel();
        MottoText = new javax.swing.JLabel();
        TitlePanel = new javax.swing.JPanel();
        TitleHome = new javax.swing.JLabel();
        TablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableOngoingBooking = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(1298, 1012));
        setName(""); // NOI18N

        MottoPanel.setBackground(new java.awt.Color(15, 129, 185));

        MottoText.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        MottoText.setForeground(new java.awt.Color(255, 255, 255));
        MottoText.setText("Rental Car - Pick, Choose, Drive");

        javax.swing.GroupLayout MottoPanelLayout = new javax.swing.GroupLayout(MottoPanel);
        MottoPanel.setLayout(MottoPanelLayout);
        MottoPanelLayout.setHorizontalGroup(
            MottoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MottoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MottoText)
                .addContainerGap(348, Short.MAX_VALUE))
        );
        MottoPanelLayout.setVerticalGroup(
            MottoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MottoPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(MottoText)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        TitlePanel.setBackground(new java.awt.Color(0, 51, 102));

        TitleHome.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        TitleHome.setForeground(new java.awt.Color(255, 255, 255));
        TitleHome.setText("Ongoing Car Booking");

        javax.swing.GroupLayout TitlePanelLayout = new javax.swing.GroupLayout(TitlePanel);
        TitlePanel.setLayout(TitlePanelLayout);
        TitlePanelLayout.setHorizontalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitlePanelLayout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addComponent(TitleHome)
                .addContainerGap(377, Short.MAX_VALUE))
        );
        TitlePanelLayout.setVerticalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitlePanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(TitleHome)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        TableOngoingBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Car ID", "Car Manufacture", "Car Model", "Production Year", "Rental Cost", "Start Date", "End Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableOngoingBooking.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(TableOngoingBooking);
        if (TableOngoingBooking.getColumnModel().getColumnCount() > 0) {
            TableOngoingBooking.getColumnModel().getColumn(0).setResizable(false);
            TableOngoingBooking.getColumnModel().getColumn(1).setResizable(false);
            TableOngoingBooking.getColumnModel().getColumn(2).setResizable(false);
            TableOngoingBooking.getColumnModel().getColumn(3).setResizable(false);
            TableOngoingBooking.getColumnModel().getColumn(4).setResizable(false);
            TableOngoingBooking.getColumnModel().getColumn(5).setResizable(false);
            TableOngoingBooking.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout TablePanelLayout = new javax.swing.GroupLayout(TablePanel);
        TablePanel.setLayout(TablePanelLayout);
        TablePanelLayout.setHorizontalGroup(
            TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        TablePanelLayout.setVerticalGroup(
            TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MottoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MottoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>                        

    // Variables declaration - do not modify                     
    private javax.swing.JPanel MottoPanel;
    private javax.swing.JLabel MottoText;
    private javax.swing.JTable TableOngoingBooking;
    private javax.swing.JPanel TablePanel;
    private javax.swing.JLabel TitleHome;
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}
