package Menus.Panel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.lang.System.Logger.Level;
import java.util.ArrayList;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import Objects.Booking;
import Objects.BookingDataFile;

/**
 *
 * @author William
 */
public class HistoryClient extends javax.swing.JPanel {

    /**
     * Creates new form HistoryClient
     */
    public HistoryClient(String clientID) {
        initComponents();
        DefaultTableModel model = (DefaultTableModel) HistoryTable.getModel();
        model.setRowCount(0);

        BookingDataFile bdf = new BookingDataFile("src\\caroodj\\Data\\Booking.txt");
        String[] bookingQuery = {"*", "*", "*", "*", "*", "*",clientID};

        ArrayList<Booking> bookingList = bdf.queryDatabase(bdf.createQuery(bookingQuery)).all();

        for (Booking booking : bookingList) {
            model.addRow(new Object[] {booking.getId(), booking.car.manufacture, booking.car.model, 
                booking.car.year, booking.car.rentalCost, booking.startDate, booking.endDate, booking.isConfirmed});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        TitlePanel = new javax.swing.JPanel();
        HistoryTitle = new javax.swing.JLabel();
        TablePanel = new javax.swing.JPanel();
        HistoryTableScroll = new javax.swing.JScrollPane();
        HistoryTable = new javax.swing.JTable();
        ShowHistoryButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1298, 1012));
        setMinimumSize(new java.awt.Dimension(1298, 1012));
        setPreferredSize(new java.awt.Dimension(1298, 1012));

        HistoryTitle.setBackground(new java.awt.Color(0, 0, 0));
        HistoryTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        HistoryTitle.setText("History Booking");
        TitlePanel.add(HistoryTitle);

        TablePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("History Booking"));
        TablePanel.setAutoscrolls(true);

        HistoryTable.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        HistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Booking ID", "Car Manufacture", "Car Model", "Production Year", "Cost", "Start Date", "End Date", "Confirmation Status"
            }
        ));
        HistoryTable.setAutoResizeMode(0);
        HistoryTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HistoryTable.setMaximumSize(new java.awt.Dimension(525, 200));
        HistoryTable.setMinimumSize(new java.awt.Dimension(525, 500));
        HistoryTable.setPreferredSize(new java.awt.Dimension(525, 200));
        HistoryTableScroll.setViewportView(HistoryTable);

        javax.swing.GroupLayout TablePanelLayout = new javax.swing.GroupLayout(TablePanel);
        TablePanel.setLayout(TablePanelLayout);
        TablePanelLayout.setHorizontalGroup(
            TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HistoryTableScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 1894, Short.MAX_VALUE)
                .addContainerGap())
        );
        TablePanelLayout.setVerticalGroup(
            TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablePanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(HistoryTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ShowHistoryButton.setText("Show History");
        ShowHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowHistoryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ShowHistoryButton)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ShowHistoryButton)
                .addContainerGap(591, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    /**
     * @param evt
     */
    private void ShowHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        String filePath = "src\\caroodj\\Data\\Booking.txt";
        File file = new File(filePath);

        try{
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader (fr);
            
            DefaultTableModel model = (DefaultTableModel)HistoryTable.getModel();
            Object[] lines = br.lines().toArray();
            
            for(int i = 0;i < lines.length; i++){
                String[] row = lines[i].toString().split(" ");
                model.addRow(row);
            }

        } catch(FileNotFoundException ex){
            JOptionPane.showMessageDialog(null,"You have no history");
        }
    }                                                 

    // Variables declaration - do not modify                     
    private javax.swing.JTable HistoryTable;
    private javax.swing.JScrollPane HistoryTableScroll;
    private javax.swing.JLabel HistoryTitle;
    private javax.swing.JButton ShowHistoryButton;
    private javax.swing.JPanel TablePanel;
    private javax.swing.JPanel TitlePanel;
    // End of variables declaration                   
}
