/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Menus.Panel;

import java.io.IOException;
import java.time.LocalDate;

import javax.swing.JOptionPane;

import Objects.Booking;
import Objects.BookingDataFile;
import Objects.Car;
import Objects.Client;
import Objects.EntityId;

/**
 *
 * @author JUSTIN
 */
public class PaymentMethod extends javax.swing.JPanel {

    /**
     * Creates new form payment
     */
    public PaymentMethod() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        optionPanel = new javax.swing.JPanel();
        paymentCombo = new javax.swing.JComboBox<>();
        confirmButton = new javax.swing.JToggleButton();
        displayPanel = new javax.swing.JPanel();
        cashPanel = new javax.swing.JPanel();
        confirmLabel = new javax.swing.JLabel();
        cardPanel = new javax.swing.JPanel();
        cardNumberField = new javax.swing.JTextField();
        cardNumberLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        cvvLabel = new javax.swing.JLabel();
        cvvField = new javax.swing.JTextField();
        dateChooser = new com.toedter.calendar.JDateChooser();

        paymentCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cash", "card" }));
        paymentCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentComboActionPerformed(evt);
            }
        });
        optionPanel.add(paymentCombo);

        confirmButton.setText("CONFIRM");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        optionPanel.add(confirmButton);

        displayPanel.setLayout(new java.awt.CardLayout());

        confirmLabel.setText("Booking will be payed on the spot");

        javax.swing.GroupLayout cashPanelLayout = new javax.swing.GroupLayout(cashPanel);
        cashPanel.setLayout(cashPanelLayout);
        cashPanelLayout.setHorizontalGroup(
            cashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(cashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(cashPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(confirmLabel)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        cashPanelLayout.setVerticalGroup(
            cashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
            .addGroup(cashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(cashPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(confirmLabel)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        displayPanel.add(cashPanel, "cashPanel");

        cardNumberLabel.setText("Card Number:");

        dateLabel.setText("Date:");

        cvvLabel.setText("CVV:");

        cvvField.setPreferredSize(new java.awt.Dimension(50, 22));

        javax.swing.GroupLayout cardPanelLayout = new javax.swing.GroupLayout(cardPanel);
        cardPanel.setLayout(cardPanelLayout);
        cardPanelLayout.setHorizontalGroup(
            cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cardNumberLabel)
                    .addComponent(dateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(cardPanelLayout.createSequentialGroup()
                        .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cvvLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cvvField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cardNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        cardPanelLayout.setVerticalGroup(
            cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardNumberLabel))
                .addGap(28, 28, 28)
                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cvvLabel)
                        .addComponent(cvvField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dateLabel)
                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        displayPanel.add(cardPanel, "cardPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(optionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>
    
    private void paymentComboActionPerformed(java.awt.event.ActionEvent evt) {                                             
        java.awt.CardLayout card = (java.awt.CardLayout) displayPanel.getLayout();
        if (paymentCombo.getSelectedItem().equals("cash")) {
            card.show(displayPanel, "cashPanel");
        } else if (paymentCombo.getSelectedItem().equals("card")) {
            card.show(displayPanel, "cardPanel");
        }
    }

    public void setData(LocalDate startdate, LocalDate endDate, Boolean isConfirmed, Boolean isCancelled, Car car, Client client, String paymentMethod) {
        this.starDate = startdate;
        this.endDate = endDate;
        this.isConfirmed = isConfirmed;
        this.isCancelled = isCancelled;
        this.car = car;
        this.client = client;
        this.paymentMethod = paymentMethod;
    }

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        Booking booking = new Booking(this.starDate, this.endDate, this.isConfirmed, this.isCancelled, this.car, this.client, (String)paymentCombo.getSelectedItem());
        booking.setId("BO:"+EntityId.generateId());
        BookingDataFile bdf = new BookingDataFile("src\\caroodj\\Data\\Booking.txt");
        try {
            bdf.addEntry(bdf.constructEntry(booking));
            JOptionPane.showMessageDialog(null, "Car has been Booked");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "An Error is Occurred!");
        }
    }     

    private LocalDate starDate;
    private LocalDate endDate;
    private Boolean isConfirmed;
    private Boolean isCancelled;
    private Car car;
    private Client client;
    private String paymentMethod;


    // Variables declaration - do not modify                     
    private javax.swing.JTextField cardNumberField;
    private javax.swing.JLabel cardNumberLabel;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JPanel cashPanel;
    private javax.swing.JToggleButton confirmButton;
    private javax.swing.JLabel confirmLabel;
    private javax.swing.JTextField cvvField;
    private javax.swing.JLabel cvvLabel;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JComboBox<String> paymentCombo;
    // End of variables declaration                   
}
