/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menus;

import java.awt.Container;

import Menus.Panel.LoginPanel;
import Menus.Panel.RegisterPanel;

/**
 *
 * @author JUSTIN
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Car Rental Service");

        Container cPane = getContentPane();
        cPane.setLayout(new java.awt.CardLayout());

        cPane.add("Register", new RegisterPanel());
        cPane.add("Login", new LoginPanel());

        pack();


    }// </editor-fold>
}
